# Generated by Django 5.2 on 2025-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='des_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
