# Generated by Django 5.2 on 2025-10-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_des_name_bill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='des_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
    ]
