# Generated by Django 5.2 on 2025-10-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_des_name_bill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
