# Generated by Django 5.2 on 2025-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.URLField(max_length=350),
        ),
    ]
