# Generated by Django 5.2 on 2025-10-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_product_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.URLField(),
        ),
    ]
