# Generated by Django 5.2 on 2025-11-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_name_expense_name2_expense_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name2',
            new_name='sec_name',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='price2',
            new_name='sec_price',
        ),
    ]
