# Generated by Django 5.2 on 2025-11-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_name2_expense_sec_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='price',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sec_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sec_price',
        ),
    ]
