# Generated by Django 5.2 on 2025-11-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_name_expense_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='price',
        ),
    ]
